### ISSUE TITLE
The tool reports an issue when reading a single txt file as input.

### ISSUE THREAD

**Issue by cychu42** [SerpentBytes/siteit#1]
## Operating Environment

Operation System: Windows 10
Node version: v16.13.2

## Issue
The tool reports an issue when reading a single txt file as input.
Entered command and output:
![image](https://user-images.githubusercontent.com/83015577/190439666-0e162cce-4acc-4b4f-8ea8-c9939db89a11.png)

What’s in the test folder:
![image](https://user-images.githubusercontent.com/83015577/190439701-b681ea9c-252a-48f4-85aa-f07431477f8e.png)

## Expected Behaviour
The tool accepts a single txt file as input and produces a html file as output.

**Comment by SerpentBytes** [comment]
@cychu42  This issue has been fixed in commit c4116ce954e119c7d08f44cbfbc3ce3cedd48d4e. When you get a chance, test out the tool. 
~Taimoor

**Comment by cychu42** [comment]
It works now, but the output file's html format is off.
html file:
![image](https://user-images.githubusercontent.com/83015577/190716531-d51b2b7a-a437-40ac-8977-6a02e2bb1575.png)

orginal txt:
![image](https://user-images.githubusercontent.com/83015577/190716570-89ec8893-0ca1-4615-9165-a0b9e8f424c9.png)
