### ISSUE TITLE
Output folder is always immediately deleted.

### ISSUE THREAD

**Issue by cychu42** [SerpentBytes/siteit#2]
## Operating Environment
Operation System: Windows 10
Node version: v16.13.2

## Issue
The tool always deletes the output folder right after successfully running it without error message. The user can’t access the output files.

## Expected Behaviour
The output folder isn't deleted and can be accedes by the user to view the result.

**Comment by SerpentBytes** [comment]
@cychu42  This issue has been fixed in commit c4116ce954e119c7d08f44cbfbc3ce3cedd48d4e. When you get a chance, test out the tool. 
~Taimoor

**Comment by cychu42** [comment]
This is no longer an issue. Nice job.
