### ISSUE TITLE
The tool doesn't generate output after creation of output folder.

### ISSUE THREAD

**Issue by cychu42** [SerpentBytes/siteit#4]
## Operating Environment
Operation System: Windows 10
Node version: v16.13.2

## Issue
As expected, the tool creates a dist output folder when it doesn't’ exist, but it should also proceed to generate output files in the folder. Instead, the output folder is empty.
Enter command and output:
![image](https://user-images.githubusercontent.com/83015577/190446303-7e16aac0-b94d-49a4-883c-4e24c5dd272e.png)

## Expected Behaviour
The tool generates output after creation of output folder.

**Comment by SerpentBytes** [comment]
@cychu42  This issue has been fixed in commit c4116ce954e119c7d08f44cbfbc3ce3cedd48d4e. When you get a chance, test out the tool. 
~Taimoor

**Comment by cychu42** [comment]
This works as expected on my end as well.
