### ISSUE TITLE
The tool inaccurately shows error message about invalid source files.

### ISSUE THREAD

**Issue by cychu42** [SerpentBytes/siteit#5]
## Operating Environment
Operation System: Windows 10
Node version: v16.13.2

## Issue
If the dist output folder doesn’t exist, the tool inaccurately shows error message about invalid source files.
When dist folder doesn’t exist:
![image](https://user-images.githubusercontent.com/83015577/190446572-8f0ac000-9430-4f10-9659-542b727845ec.png)

When dist folder exists:
![image](https://user-images.githubusercontent.com/83015577/190446619-c0a2cefd-bd70-408a-90b4-2ac317cb5446.png)

Content of the input folder:
![image](https://user-images.githubusercontent.com/83015577/190446651-148bb5ae-7207-49ac-8363-912d8dd879fb.png)

## Expected Behaviour
The tool doesn't show any message about the source files when they are valid, regardless of whether the output folder is missing.

**Comment by SerpentBytes** [comment]
Fixed in commit  15a74713d733ba92c79d9ec4c172f520eb45fdb1
~Taimoor
