### ISSUE TITLE
"siteit -i ./source_directory" command generates an error.

### ISSUE THREAD

**Issue by cychu42** [SerpentBytes/siteit#6]
## Operating Environment
Operation System: Windows 10
Node version: v16.13.2
Command-line shell: PowerShell v5.1.19041.1682

## Issue
On my machine, the tool doesn’t run when entering command "siteit -i ./source_directory" as instructed in help guide.
Enter command and output:
![image](https://user-images.githubusercontent.com/83015577/190448018-dfcc6b38-7763-4f16-9efd-a88d0084c495.png)

It does run when running index.js directly:
![image](https://user-images.githubusercontent.com/83015577/190448028-b72b249b-743e-4460-b76d-63987009906a.png)

I'm unfortunately not sure whether it's related to my setup or this is a general issue that also occurs for you.

## Expected Behaviour
The tool runs like running index.js directly.

**Comment by SerpentBytes** [comment]
@cychu42  Can you try running the tool using `node ./index -i` from PowerShell?

**Comment by SerpentBytes** [comment]
@cychu42 I have updated the `README.MD` file with the installation process. [Click here](https://github.com/SerpentBytes/siteit#installation) to see how to run the tool locally on Windows operating system.

See below:
<img width="1575" alt="fixed-issuw" src="https://user-images.githubusercontent.com/50856799/190501953-21b38413-436b-4b48-9b64-09177a97a9c4.png">
