### ISSUE TITLE
Tool doesn't work with filenames that have space

### ISSUE THREAD

**Issue by Myrfion** [SerpentBytes/siteit#7]
I tried to run command `siteit --input Silver Blaze.txt` and got the following error messages: 
`-- ERROR Invalid or non-existing source supplied --
-- ERROR Invalid or non-existing source supplied --`

**Comment by SerpentBytes** [comment]
Fixed in commit  15a74713d733ba92c79d9ec4c172f520eb45fdb1
~Taimoor
