### ISSUE TITLE
The Resulted HTML is not valid

### ISSUE THREAD

**Issue by Myrfion** [SerpentBytes/siteit#8]
I ran the HTML validation on the https://validator.w3.org/nu/#file, resulting in an issue `Start tag seen without seeing a doctype first. Expected <!DOCTYPE html>.`

![image](https://user-images.githubusercontent.com/32075241/190835599-7ebf3a33-0ef3-45be-b9b8-716ca12d73e3.png)

**Comment by SerpentBytes** [comment]
This issue has been fixed in the commit e7c25058290feb0ad97335d3c358336f587add4c

See below:

<img width="1786" alt="Screen Shot 2022-09-17 at 9 10 56 PM" src="https://user-images.githubusercontent.com/50856799/190881426-c434cfe3-1383-4239-bd30-5b517de73cf7.png">

~Taimoor
